name: concepta_challenge
description: A new Flutter for concepta.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.3 <3.0.0'
  
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  hive_flutter: ^1.1.0
  pub_api_client: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter  
  flutter_lints: ^2.0.0
  faker: ^2.1.0
  mocktail: ^0.3.0

flutter:
  uses-material-design: true